language: node_js

install:
  - npm install -g codecov

scripts: 
  - npm test
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov

install:
  - npm install -g codecov
  